name: delete release
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest release
        id: get_latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          draft: true
          tag_name: ${{ GITHUB.HEAD_REF }}
        continue-on-error: true
      - name: Delete Release
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get_latest_release.outputs.id }}
          suppress_errors: false
